runtime: python39

entrypoint: gunicorn -b :$PORT api:app

instance_class: F2

env_variables:
  PORT: 8000

handlers:
- url: /.*
  script: auto

requirements:
  - tensorflow
  - numpy
  - keras
  - Flask
  - gunicorn
